#!/usr/bin/env sh

if [[ "$#" -ne 4 ]]; then
	echo "Usage: vidcut <input_file> <start_time> <end_time> <out_file>"
	#echo "Usage: vidcut <input_file> <start_time> <duration> <out_file>"
	exit 1
fi

# Cut accurately
ffmpeg -i $1 -ss $2 -to $3 $4 

# Cut quickly
# ffmpeg -ss $2 -i $1  -t $3 -c copy $4 
