#!/bin/sh

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &
picom --config ${XDG_CONFIG_HOME:-$HOME/.config}/picom/picom.conf -b --experimental-backends
xbindkeys -f ${XDG_CONFIG_HOME:-$HOME/.config}/xbindkeysrc 
